version: "3"

volumes:
  staticfiles:

services:

  db:
    container_name: megafon_database
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initb.d/init.sh
    environment:
      - POSTGRES_DB=megafon_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: megafon_web
    build: .
    command: gunicorn --workers=3 megafonTest.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/static
    env_file:
      - ./.env
    entrypoint:
      - ./entrypoint.sh
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    container_name: megafon_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    depends_on:
      - web
