# Generated by Django 3.2.12 on 2022-03-19 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('last_action_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of last activity')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('exp_date', models.DateField(verbose_name='Expiration date')),
                ('minutes_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minutes volume')),
                ('sms_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='SMS volume')),
                ('traffic_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Traffic volume')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('service_type', models.CharField(choices=[('C', 'Call'), ('S', 'SMS'), ('T', 'Traffic')], max_length=1, verbose_name='Type of service')),
                ('units_spent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount of units spent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='megafon_api.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='active_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='megafon_api.tariff', verbose_name='Active tariff'),
        ),
    ]
